name: sluggi-typo3-14
type: typo3
docroot: public
php_version: "8.4"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "11.4"
nodejs_version: "22"
disable_settings_management: false
corepack_enable: true

additional_fqdns:
  - e2e.sluggi-typo3-14.ddev.site

hooks:
  post-start:
    - exec-host: bash .ddev/commands/host/install
