name: Crowdin

on:
  push:
    branches:
      - main
    paths:
      - '**.xlf'
  workflow_dispatch:

jobs:
  sync:
    name: Synchronize with Crowdin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Upload sources
        uses: crowdin/github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: '.crowdin.yml'
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          crowdin_branch_name: 'main'
          upload_sources: true
          upload_translations: false
          download_sources: false
          download_translations: false
